Repository qaml-bootcamp-java-selenium-jul2022/proyectoFinalEquipoUno, pull requests merged in 2022-08, with the labels that each got.

#2 Agregando clase Cliente, Enum PagoElectronico y ClienteTest
  src/main/java/EjerciciosProyectoFinal/Cliente.java
  src/main/java/EjerciciosProyectoFinal/PagoElectronico.java
  src/test/java/EjerciciosProyectoFinal/ClienteTest.java
Labels: Alvaro

#3 Agrego Clase Abstracta Prenda y Clases hijas Blusa,Sombrero y sus res…
  src/main/java/EjerciciosProyectoFinal/Blusa.java
  src/main/java/EjerciciosProyectoFinal/EstadosDeMexico.java
  src/main/java/EjerciciosProyectoFinal/Prenda.java
  src/main/java/EjerciciosProyectoFinal/Sombrero.java
  src/test/java/EjerciciosProyectoFinal/BlusaTest.java
  src/test/java/EjerciciosProyectoFinal/SombreroTest.java
Labels: Alvaro

#4 Agregando clases Falda, Pantalon y sus tests
  src/main/java/EjerciciosProyectoFinal/Falda.java
  src/main/java/EjerciciosProyectoFinal/Pantalon.java
  src/main/java/EjerciciosProyectoFinal/Prenda.java
  src/test/java/EjerciciosProyectoFinal/FaldaTest.java
  src/test/java/EjerciciosProyectoFinal/PantalonTest.java
Labels: Susana

#6 Agregando clase Venta y Renta con sus tests y cambiando CategoriaPren…
  src/main/java/EjerciciosProyectoFinal/Blusa.java
  src/main/java/EjerciciosProyectoFinal/CategoriaPrenda.java
  src/main/java/EjerciciosProyectoFinal/Falda.java
  src/main/java/EjerciciosProyectoFinal/Pantalon.java
  src/main/java/EjerciciosProyectoFinal/Prenda.java
  src/main/java/EjerciciosProyectoFinal/Renta.java
  src/main/java/EjerciciosProyectoFinal/Sombrero.java
  src/main/java/EjerciciosProyectoFinal/Venta.java
  src/main/java/EjerciciosProyectoFinal/Zapato.java
  src/test/java/EjerciciosProyectoFinal/BlusaTest.java
  src/test/java/EjerciciosProyectoFinal/FaldaTest.java
  src/test/java/EjerciciosProyectoFinal/PantalonTest.java
  src/test/java/EjerciciosProyectoFinal/RentaTest.java
  src/test/java/EjerciciosProyectoFinal/SombreroTest.java
  src/test/java/EjerciciosProyectoFinal/VentaTest.java
  src/test/java/EjerciciosProyectoFinal/ZapatoTest.java
Labels: Proyecto Final
